version: '3.8'
services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - my_network
    depends_on:
      - db 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp  
    volumes:
      - db_data:/var/lib/mysql
      - ./ims480.sql:/docker-entrypoint-initdb.d/ims480.sql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
